---
title: "STAT 380 Final Project"
author: "Greg Westfall and TJ Schaeffer"
output: html_notebook
---

```{r}
# Packages
library(mdsr)
library(readr)
library(dplyr)
library(tidyr)
library(tidytext)
library(wordcloud)
library(readtext)
library(class)
library(tibble)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(randomForest)

```


```{r}
# Reading in Terrorism 
terrorism <- read.table(unz("globalterrorismdb_0718dist.csv.zip", "globalterrorismdb_0718dist.csv"), nrows=181692, header=T, fill =T, quote="\"", sep=",")
# Reading in Econ Data
econData <- read.csv("WEO_Data.csv")
```


```{r}
terrorism_deaths <-
  terrorism %>%
  group_by(country_txt) %>%
  summarise(attacks = n(), deaths = sum(na.omit(nkill))) %>%
  arrange(desc(deaths))

terrorism_deaths
```

```{r}
terrorism_words <-
  terrorism %>%
  sample(5000) %>%
  select(attacktype1_txt)

 write.table(terrorism_words, file = "terrorism_words.txt", quote = FALSE,
            sep = "", row.names = FALSE, col.names = FALSE)

terrorism_txt <- 
  readtext(file = "terrorism_words.txt") %>%
  as_tibble()

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " "))
terrorism_txt <- tm_map(terrorism_words, toSpace, "/")
terrorism_words <- tm_map(terrorism_words, toSpace, "@")
terrorism_words <- tm_map(terrorism_words, toSpace, "\\|")

head(terrorism_txt)
```

```{r}
wordcloud("terrorism_words.txt", max.words = 10)

```


```{r}
terrorism %>%
  sample(5000) %>%
  ggplot(aes(x = longitude, y = latitude)) +
  geom_point()
```

```{r}
terrorism %>%
  filter(country_txt == "United States") %>%
  filter(longitude < 0) %>%
  filter(nkillus > 0) %>%
  ggplot(aes(x = longitude, y = latitude)) +
  geom_point(aes(color = nkill))
```

```{r}
# Using apply to change values in data frame to numbers
econNumeric <- apply(X = econData[,5:30], FUN = as.numeric, MARGIN = 2)

econDataNew <-
  econData %>%
  select(c(1:4))
  
econData2 <-
  as.data.frame(econNumeric)

econDataNew <-
  econDataNew %>%
  cbind(econData2)

econDataNew
```

```{r}
# Using gather function to make data frame tidy
econDataTidy <-
  econDataNew %>%
  gather(key = "Year", value = "Value", 5:30)

econDataTidy

```

```{r}
# Creating average of values over the 26 years found in the data frame
econAverages <-
  econDataTidy %>%
  group_by(Country, Subject.Descriptor, Units) %>%
  summarise(average = mean(na.omit(Value)))

econAverages

```

```{r}
# User-defined function to create data frame based off subject indicator
create_deaths_table <- function(x, y){
  econAverages %>%
    filter(Subject.Descriptor == x, Units == y) %>%
    rename("country_txt" = "Country") %>%
    left_join(terrorism_deaths, by = "country_txt") %>%
    filter(!is.na(attacks) & !is.na(deaths)) %>%
    rename("Country" = "country_txt") %>%
    mutate(above_below = ifelse(attacks >= 1073.441, "above", "below"))
}

```

```{r}
# Data frame with population and attacks/deaths
PopDeaths <- create_deaths_table("Population", "Persons")
PopDeaths
```

```{r}
# logistic regression
pop_logit <- lm(attacks ~ average, data = PopDeaths)
msummary(pop_logit)

```

```{r}
# logistic confusion matrix
pop_logitProb <- predict(pop_logit, newdata = PopDeaths, type = "response")
pop_logit <- ifelse(pop_logitProb > mean(PopDeaths$attacks), yes = "above", "below")
confusion_logit_pop <- tally(pop_logit ~ above_below, data = PopDeaths, 
                             format = "count")
confusion_logit_pop

```

```{r}
# model accuracy
pop_logit_acc <- sum(diag(confusion_logit_pop)) / nrow(PopDeaths) * 100
pop_logit_acc

```


```{r}
# Data frame with GDP
GDPDeaths <- create_deaths_table("Gross domestic product per capita, constant prices",
                                 "Purchasing power parity; 2011 international dollar")
GDPDeaths

```

```{r}
# logistic regression
gdp_logit <- lm(attacks ~ average, data = GDPDeaths)
msummary(gdp_logit)

```

```{r}
# logistic confusion matrix
gdp_logitProb <- predict(gdp_logit, newdata = GDPDeaths, type = "response")
gdp_logit <- ifelse(gdp_logitProb > mean(GDPDeaths$attacks), yes = "above", "below")
confusion_logit_gdp <- tally(gdp_logit ~ above_below, data = GDPDeaths, 
                             format = "count")
confusion_logit_gdp

```

```{r}
# model accuracy
gdp_logit_acc <- sum(diag(confusion_logit_gdp)) / nrow(GDPDeaths) * 100
gdp_logit_acc

```

```{r}
# Data Frame with inflation
InflationDeaths <- create_deaths_table("Inflation, average consumer prices",
                                       "Index")
InflationDeaths
```

```{r}
# logistic regression
inflation_logit <- lm(attacks ~ average, data = InflationDeaths)
msummary(inflation_logit)

```

```{r}
# logistic confusion matrix
inflation_logitProb <- predict(inflation_logit, newdata = InflationDeaths, 
                               type = "response")
inflation_logit <- ifelse(inflation_logitProb > mean(InflationDeaths$attacks), 
                          yes = "above", "below")
confusion_logit_inflation <- tally(inflation_logit ~ above_below, 
                                   data = InflationDeaths, format = "count")
confusion_logit_inflation

```

```{r}
# model accuracy
inflation_logit_acc <- sum(diag(confusion_logit_inflation)) / 
                           nrow(InflationDeaths) * 100
inflation_logit_acc

```

```{r}
# Data frame involving total country spending
SpendingDeaths <- create_deaths_table("General government total expenditure",
                                      "Percent of GDP")
SpendingDeaths
```

```{r}
# logistic regression
spending_logit <- lm(attacks ~ average, data = SpendingDeaths)
msummary(spending_logit)

```

```{r}
# logistic confusion matrix
spending_logitProb <- predict(spending_logit, newdata = SpendingDeaths, 
                              type = "response")
spending_logit <- ifelse(spending_logitProb > mean(SpendingDeaths$attacks), 
                         yes = "above", "below")
confusion_logit_spending <- tally(spending_logit ~ above_below, data = SpendingDeaths, 
                                  format = "count")
confusion_logit_spending

```

```{r}
# model accuracy
spending_logit_acc <- sum(diag(confusion_logit_spending)) / nrow(SpendingDeaths) * 100
spending_logit_acc

```

```{r}
# Data frame involving percent change in imported goods and services
ImportDeaths <- create_deaths_table("Volume of imports of goods and services",
                                    "Percent change")
ImportDeaths

```

```{r}
# logistic regression
import_logit <- lm(attacks ~ average, data = ImportDeaths)
msummary(import_logit)

```

```{r}
# logistic confusion matrix
import_logitProb <- predict(import_logit, newdata = ImportDeaths, type = "response")
import_logit <- ifelse(import_logitProb > mean(ImportDeaths$attacks), 
                       yes = "above", "below")
confusion_logit_import <- tally(import_logit ~ above_below, data = ImportDeaths, 
                             format = "count")
confusion_logit_import

```

```{r}
# model accuracy
import_logit_acc <- sum(diag(confusion_logit_import)) / nrow(ImportDeaths) * 100
import_logit_acc

```

```{r}
YearEconData <-
  econDataTidy %>%
  filter(Subject.Descriptor == "Population") 

year_terrorism_deaths <-
  terrorism %>%
  group_by(iyear) %>%
  filter(iyear >= 1999) %>%
  summarise(attacks = n(), deaths = sum(na.omit(nkill))) %>%
  rename("Year" = "iyear") %>%
  arrange(Year)

YearEconDataClean <-
  YearEconData %>%
  mutate(Year = as.numeric(gsub("X", "", Year))) %>%
  group_by(Year) %>%
  filter(Year <= 2017) %>%
  summarise(worldPop = sum(na.omit(Value)))

ggplot(data = year_terrorism_deaths, aes(x = Year, y = attacks)) +
  geom_point(color = "red", shape = 15) + geom_line(color = "red") +
  geom_point(aes(x = Year, y = worldPop), color = "blue", data = YearEconDataClean) +
  geom_line(aes(x = Year, y = worldPop), color = "blue", data = YearEconDataClean) +
  ylab("Attacks/World Population")
```

```{r}
td2 <- terrorism_deaths[-c(1)]

td2 <-
  td2 %>%
  select(attacks, deaths) %>%
  arrange(desc(attacks)) %>%
  head(25)

td_top_25 <-
  terrorism_deaths %>%
  arrange(desc(attacks)) %>%
  head(25)

td_std <-
  scale(td2) %>%
  as.data.frame()

td_dist <- dist(td_std)

td_dendo <-
  td_dist %>%
  hclust(method = "complete")

labels <- td_top_25$country_txt

td_dendo %>%
  plot(cex = 0.9, labels = labels, lwd = 2,
       main = "Countries with Most Terrorist Attacks")
```

```{r}
Top_6_Countries <-
  terrorism %>%
  filter(country_txt == "Iraq" | country_txt == "Pakistan" | 
         country_txt == "Afghanistan" | country_txt == "India" | 
         country_txt == "Colombia" | country_txt == "Philippines") %>%
  group_by(country_txt, iyear) %>%
  summarise(Attacks = n())

Top_6_Countries %>%
  ggplot(aes(x = iyear, y = Attacks)) +
  geom_point() + geom_line() +
  facet_wrap(~country_txt)

```


